<a href="https://colab.research.google.com/github/jtunde/Python/blob/main/cn2%20CNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Single Step Convolutional Nueral Network

# CNN Time Series Forecasting

In [7]:
#Importing Libraries
from numpy import array
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers.convolutional import Conv1D
from keras.layers.convolutional import MaxPooling1D
import pandas as pd

In [5]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [12]:
data = pd.read_csv('drive/MyDrive/data.csv')
print(data.head())
date=list(data['RON'])

         TIME     RON
0  2021-01-01  4.9493
1  2021-01-02  4.9493
2  2021-01-03  4.9493
3  2021-01-04  4.8713
4  2021-01-05  4.8721


In [13]:
# split a univariate sequence into samples
def split_sequence(sequence, steps):
  X, y = list(), list()
  for start in range(len(sequence)):
    # define the end index of the sequence
    end_index = start + steps
    # to check if end_index stays in the allowable limit
    if end_index > len(sequence)-1:
      break
    # extract input and output parts of the sequence
    sequence_x, sequence_y = sequence[start : end_index], sequence[end_index]
    X.append(sequence_x)
    y.append(sequence_y)
  return array(X), array(y)

In [15]:
#raw_sequence = [100, 110, 120, 130, 140, 150 ,160, 170, 180 ,190]

# choose a number of time steps
steps = 3

# split into samples
#X, y = split_sequence(raw_sequence, steps)

X, y = split_sequence(date, steps)

print("**************************************************************")
print("The input raw sequence on which we will test our CNN model")
#print(raw_sequence)
print(date)
print("**************************************************************")
print("The features (X) ,lagged values of time series, for our CNN model")
print(X)
print("**************************************************************")
print("The respective observed values (y) of the sequence for training in CNN model")
print(y)
print("**************************************************************")

**************************************************************
The input raw sequence on which we will test our CNN model
[4.9493, 4.9493, 4.9493, 4.8713, 4.8721, 4.872, 4.8712, 4.8708, 4.8708, 4.8708, 4.8705, 4.8713, 4.8725, 4.8738, 4.8733, 4.8733, 4.8733, 4.8743, 4.8744, 4.8738, 4.874, 4.874, 4.874, 4.874, 4.8744, 4.8748, 4.8753, 4.8761, 4.875, 4.875, 4.875, 4.8735, 4.8743, 4.8734, 4.8755, 4.8747, 4.8747, 4.8747, 4.8748, 4.8753, 4.8752, 4.8745, 4.8746, 4.8746, 4.8746, 4.8753, 4.876, 4.875, 4.8751, 4.8758, 4.8758, 4.8758, 4.8758, 4.876, 4.8749, 4.8748, 4.875, 4.875, 4.875, 4.8749, 4.8762, 4.8775, 4.8813, 4.8813, 4.8813, 4.8813, 4.8852, 4.887, 4.8865, 4.884, 4.885, 4.885, 4.885, 4.8845, 4.8868, 4.8874, 4.8858, 4.8853, 4.8853, 4.8853, 4.8862, 4.8893, 4.888, 4.8865, 4.8878, 4.8878, 4.8878, 4.9025, 4.921, 4.9223, 4.9088, 4.9088, 4.9088, 4.9088, 4.9088, 4.9175, 4.9185, 4.9198, 4.9198, 4.9198, 4.9198, 4.9203, 4.9223, 4.924, 4.925, 4.9263, 4.9263, 4.9263, 4.926, 4.9278, 4.926, 4.9274, 4.9245

In [19]:
# reshape 2D input data to 3D input data
features = 1
X = X.reshape((X.shape[0], X.shape[1], features))

print("After reshaping , the shape of input X")
print(X.shape)
print("**************************************************************")
print("**************************************************************")
print("The final form of input feature matrix X")
print(X)
print("**************************************************************")
print("**************************************************************")
print("Feature matrix X is ready for input to CNN model.We have used feature engineering" 
    +"to convert a sequence to matrix with image matrix shape to find patterns in sequence")
print("**************************************************************")

After reshaping , the shape of input X
(334, 3, 1)
**************************************************************
**************************************************************
The final form of input feature matrix X
[[[4.9493]
  [4.9493]
  [4.9493]]

 [[4.9493]
  [4.9493]
  [4.8713]]

 [[4.9493]
  [4.8713]
  [4.8721]]

 ...

 [[4.9498]
  [4.9498]
  [4.951 ]]

 [[4.9498]
  [4.951 ]
  [4.9467]]

 [[4.951 ]
  [4.9467]
  [4.9488]]]
**************************************************************
**************************************************************
Feature matrix X is ready for input to CNN model.We have used feature engineeringto convert a sequence to matrix with image matrix shape to find patterns in sequence
**************************************************************


In [20]:
# Defining model Architecture
model = Sequential()
model.add(Conv1D(filters=64, kernel_size=2, activation='relu', input_shape=(steps,
features)))
model.add(MaxPooling1D(pool_size=2))
model.add(Flatten())
model.add(Dense(100, activation='relu'))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')

In [21]:
# fit model
model.fit(X, y, epochs=10, verbose=0)

In [32]:
#Testing the Model
x_input = array(date[:3])
print(x_input)
x_input = x_input.reshape((1, steps, features))
y_pred = model.predict(x_input, verbose=0)
print("**************************************************************")
#print(f"The next predicted value for the sequence {raw_sequence} is")
print(f"The next predicted value for the sequence {date} is")
print(y_pred)
print("**************************************************************")



[4.9493 4.9493 4.9493]
**************************************************************
The next predicted value for the sequence [4.9493, 4.9493, 4.9493, 4.8713, 4.8721, 4.872, 4.8712, 4.8708, 4.8708, 4.8708, 4.8705, 4.8713, 4.8725, 4.8738, 4.8733, 4.8733, 4.8733, 4.8743, 4.8744, 4.8738, 4.874, 4.874, 4.874, 4.874, 4.8744, 4.8748, 4.8753, 4.8761, 4.875, 4.875, 4.875, 4.8735, 4.8743, 4.8734, 4.8755, 4.8747, 4.8747, 4.8747, 4.8748, 4.8753, 4.8752, 4.8745, 4.8746, 4.8746, 4.8746, 4.8753, 4.876, 4.875, 4.8751, 4.8758, 4.8758, 4.8758, 4.8758, 4.876, 4.8749, 4.8748, 4.875, 4.875, 4.875, 4.8749, 4.8762, 4.8775, 4.8813, 4.8813, 4.8813, 4.8813, 4.8852, 4.887, 4.8865, 4.884, 4.885, 4.885, 4.885, 4.8845, 4.8868, 4.8874, 4.8858, 4.8853, 4.8853, 4.8853, 4.8862, 4.8893, 4.888, 4.8865, 4.8878, 4.8878, 4.8878, 4.9025, 4.921, 4.9223, 4.9088, 4.9088, 4.9088, 4.9088, 4.9088, 4.9175, 4.9185, 4.9198, 4.9198, 4.9198, 4.9198, 4.9203, 4.9223, 4.924, 4.925, 4.9263, 4.9263, 4.9263, 4.926, 4.9278, 4.926, 4.9274, 